version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: kingpork-image
    container_name: kingpork-container
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - kingpork-network
  db:
    image: mysql:5.7
    container_name: kingpork-db-container
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - kingpork-network
  nginx:
    image: nginx:latest
    container_name: kingpork-nginx-container
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - kingpork-network
networks:
  kingpork-network:
    driver: bridge